homeFragment to develop
Android-3rd-team-3/Y-Media-App pull request #11
Opened 2024-05-17 07:45 UTC by Winterwood0118

homeViewmodel에 API 연결
spinner 이용해서 카테고리, 카테고리 별 채널 검색 구현 
필요없는 파일 정리 
카테고리 엔티티 수정

2024-05-17 09:26 UTC, winteryy requested changes
일단 눈에 보이는 것만 코멘트 남겼습니다
전반적으로 로직 이해도도 높으시고, LiveData랑 MVVM 패턴도 이미 알고 계셔서
이 외에 크게 짚이는 것은 아직 안보이네용

2024-05-17 09:26 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
>              }
apply 내에 apply가 중첩되는 형태는 모호성 문제를 야기할 수 있습니다

물론 레이블을 명시해서 처리할 순 있겠지만, 가독성도 떨어지기 때문에
중첩되는 스코프 함수를 사용할 땐 코드 블록에 수신 객체를 명시적으로 전달하는
also, let을 사용한 이후에, 파라미터 명을 지정하는게 나을 것 같습니다!

2024-05-17 09:26 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
> +    }
`ViewModel`로부터 직접 데이터를 리턴 받는 형태는 지양해야 하는 형태로 알고 있습니다!
`View`에서 `Observe` 중인 `LiveData`를 이용해 `View`차원에서 해당 로직을 구현할 수도 있을 거 같습니다 

그리고 항상 0번째 값으로 "Category"가 들어가게 한 건 `Spinner`의 타이틀처럼 노출하기 위해서인가요?
전체 로직을 보았을 때, 어차피 첫 카테고리로 초기 리스트 항목들이 셋팅 될테니 받아온 카테고리명을 바로 노출해도 되지 않을까 싶습니다
오히려 다른 카테고리를 선택했다가 `Spinner`내에서 "Category"를 누르면 첫 카테고리가 뜨는 상황이 발생할 것 같습니다


+ 실제로 그렇게 되네요

https://github.com/Android-3rd-team-3/Y-Media-App/assets/104819764/c501c940-4e69-4847-b644-f30da20304e4

2024-05-17 09:26 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
> +    }
이것도 마찬가지로 직접적인 값을 리턴하고 있습니다.

어디에 이용되는지 찾아봤는데, 이런식으로 CategoryId 값을 전달하는 것보다는
아예 `Spinner`에 필요한 adapter를 커스텀해서 Category 자체를 바인딩 할 수 있도록 해보는 것도 좋을 것 같습니다!

그렇게 되면 아이템이 선택됐을 때, 바인딩된 아이템으로부터 CategoryId도 불러올 수 있고
위에서 말씀드렸던 부분도 굳이 `View`에서 로직을 구현할 필요도 없어질 것 같네요

2024-05-17 09:26 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
> +                onItemSelectedListener = object : AdapterView.OnItemSelectedListener{
apply 없이 구현해도 될 것 같습니다

2024-05-17 09:26 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
> +                        }
이런 곳도 apply가 굳이 필요 없어보이네요!

homeViewModel의 프로퍼티와 메소드에 여러 번 접근이 필요한 상황도 아니고,
수정된 homeViewModel이 재사용 되어야 할 상황도 아닌 것 같습니다

`homeViewModel.getCategoryVideoList(findCategoryIdByPosition(position)` 과 같이 써도 무방할 것 같네용

2024-05-17 09:48 UTC, AndroidJeong approved these changes

2024-05-17 10:22 UTC, Winterwood0118 commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
> +    }
뷰모델에서 리뷰 남겨주신 부분은 어댑터 커스텀 찾아보고 한번 해보겠습니다

2024-05-19 10:55 UTC, winteryy approved these changes
전반적으로 완성도나 퍼포먼스에 대한 욕심이 보이셔서
사소한 부분도 코멘트 드렸습니다

수정을 하셔도, 안 하셔도 무방하고 바로 merge하셔도 됩니다
고생하셨습니다!!

2024-05-19 10:55 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeSpinnerAdapter.kt
> +        return view
어댑터 내에서 `View` 재사용 하시려고 이런 코드를 작성하신거죠? 좋은 코드인 것 같습니다👍

퍼포먼스에 욕심이 있으신거 같으니 사족을 붙이자면,
이왕 `Context`를 파라미터로 받아온다면 `LayoutInflater.from()`도 생성 비용이 발생하기 때문에
어댑터 내에 `LayoutInflater`를 하나 프로퍼티로 선언해 초기화 해두고, 해당 `LayoutInflater`를 필요할 때 재사용 할 수 있을 것 같습니다

2024-05-19 10:55 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
> +                binding.spinnerCategory.adapter = HomeSpinnerAdapter(requireActivity(), it)
카테고리 리스트가 갱신될 때마다, 매번 어댑터를 새로 생성하는 것은 비효율적인 것 같습니다(물론 카테고리 리스트가 갱신될 일이 잦지는 않습니다)
어댑터를 매번 새로 생성한다면, 어댑터 코드 내에서 애써 최적화 해 놓은 코드들이 의미가 없어집니다
다른 어댑터들처럼, `notifyDataSetChanged()`를 활용해보면 좋을 것 같습니다, 대신에 이를 위해서 어댑터 내에서 코드 수정이 약간 필요해 보일 것 같네요!

2024-05-19 10:55 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeViewModel.kt
> +        return sb.toString()
코틀린의 컬렉션 API와 `Iterable.joinToString()`을 사용해볼 수 있을 것 같네요

2024-05-19 10:55 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/home/HomeFragment.kt
> +                getCategoryChannelList()
카테고리 채널 리스트 갱신을 `ViewModel` 내에서 알아서 동작하도록 하는 것도 괜찮을 것 같습니다
순수하게 `ViewModel` 내부에서만 변하는 로직이라 `View`까지 끌고 올 이유는 없어 보입니다!

2024-05-20 00:49 UTC, Winterwood0118 commented
해당 부분 잠시 만져봤는데 시간이 좀 걸릴 것 같아 일단 merge 하겠습지다! 감사합니다!

2024-05-20 00:49 UTC, merged