searchFragment 금일까지 작업한 사항 입니다.
Android-3rd-team-3/Y-Media-App pull request #13
Opened 2024-05-17 10:16 UTC by eddy-PMS

searchFragment 금일까지 작업한 사항 입니다.

2024-05-17 11:00 UTC, Winterwood0118 requested changes
pr 넣으실 때 reviewer에 본인을 제외한 4분 모두를 추가해주세요
또한 assignees에 본인을 추가해주세요
코멘트 넣은 부분 반영해주시면 approve 하겠습니다
수정사항 반영하는 방법 모르시면 말씀주세요

2024-05-17 11:00 UTC, Winterwood0118 commented on app/build.gradle.kts
해당 코드 중 67번째 줄 코드는 동일파일 52번째 줄에서 glide를 사용중이기 때문에 지워주시면 되겠습니다.
68번째 줄도 소스코드에서 사용하신게 아니라면 지워주시면 되겠습니다.

2024-05-17 11:00 UTC, Winterwood0118 commented on app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
>  import com.example.ymediaapp.presentation.entity.YoutubeChannelResultEntity
사용하지 않는 import는 지워주세요

2024-05-17 11:31 UTC, Winterwood0118 approved these changes
반영 감사합니다. searchRepositoryImpl의 해당 import는 일부러 남겨두신건가요?

2024-05-17 11:33 UTC, winteryy approved these changes
다른 부분은 다른 분들이 봐주신 것도 있고
병합해서 확인할 부분들이 좀 있는 것 같아 승인했습니다
수고하셨습니다~

2024-05-17 11:33 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
> +                layoutManager = StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL)
`StaggeredGridLayoutManager`를 사용하신 이유가 있나요?

2024-05-20 02:51 UTC, eddy-PMS commented on app/build.gradle.kts
해결했습니다.

2024-05-20 02:57 UTC, eddy-PMS commented on app/src/main/java/com/example/ymediaapp/data/repository/SearchRepositoryImpl.kt
>  import com.example.ymediaapp.presentation.entity.YoutubeChannelResultEntity
해결했습니다.

2024-05-20 02:59 UTC, eddy-PMS commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
> +                layoutManager = StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL)
큰 이유없이 사용했습니다. 좀 더 찾아보고 GridLayoutManager 적용할 수 있으면 변경 후 말씀 드리겠습니다.

2024-05-20 03:08 UTC, eddy-PMS commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
> +                layoutManager = StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL)
GridLayoutManager로 수정했습니다.

2024-05-20 03:11 UTC, Winterwood0118 approved these changes

2024-05-20 03:11 UTC, eddy-PMS commented
금일까지 작업 내역 입니다.

2024-05-20 03:12 UTC, merged