Feature/search fragment
Android-3rd-team-3/Y-Media-App pull request #19
Opened 2024-05-20 11:34 UTC by eddy-PMS

2024-05-20 11:48 UTC, Winterwood0118 requested changes
고생하셨습니다! MyVideoViewModel 코멘트만 적용해주시면 큰 문제는 없을 것 같습니다.

2024-05-20 11:48 UTC, Winterwood0118 commented on app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
>          }
임시로 바꾼 부분은 pr하기전에 rollback 해주세용 conflict 발생가능성이 높아집니다!
list.value -> list

2024-05-20 11:48 UTC, Winterwood0118 commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchAdapter.kt
>  }
굉장히 깔끔하게 예외처리까지 된 코드네요 잘하셨습니다. 혹시 53번째 줄에 Locale.English 부분은 지역 설정하는 부분으로 알고있는데 getDefault()가 아닌 English를 사용하신 이유가 있을까요?

2024-05-20 11:48 UTC, Winterwood0118 commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
>          }
잘 하셨습니다! 위에 사용하신 with(binding) 활용해도 좋을 것 같습니다. 반대로 62번 줄의 경우에는 binding의 중복 호출이 없으니 with를 제거하고 사용해도 좋을 것 같고 62~67번 줄은 init view가 아닌 별개의 메서드를 만드는것이 좋아보입니다. 큰 부분은 아니니 나중에 수정하셔도 괜찮을 것 같습니다.

2024-05-21 01:18 UTC, eddy-PMS commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchAdapter.kt
>  }
날짜시간 데이터가 "Thu Apr 27 00:30:30 GMT 2023" 이런식으로 표출되어서 영어로 인식하도록 했더니 문제가 없었습니다.

2024-05-21 01:21 UTC, eddy-PMS commented on app/src/main/java/com/example/ymediaapp/presentation/search/SearchFragment.kt
>          }
네 감사합니다. 좀 더 찾아보고 나중에 변경하겠습니다!

2024-05-21 01:23 UTC, eddy-PMS commented on app/src/main/java/com/example/ymediaapp/presentation/my_video/MyVideoViewModel.kt
>          }
list로 수정하고 다시 push 하였습니다.

2024-05-21 01:27 UTC, Winterwood0118 commented
확인했습니다

2024-05-21 01:46 UTC, Winterwood0118 approved these changes

2024-05-21 01:51 UTC, AndroidJeong approved these changes

2024-05-21 01:52 UTC, merged