pr 관련 수정, room 코드 작성
Android-3rd-team-3/Y-Media-App pull request #5
Opened 2024-05-16 10:18 UTC by AndroidJeong

db 폴더에 room 코드 작성했습니다

2024-05-16 10:46 UTC, Winterwood0118 requested changes
굿입니다 해당 부분만 지워주시고 commit -> push 하신 다음 알려주세요

2024-05-16 10:46 UTC, Winterwood0118 commented on build.gradle.kts
> +//}
변경 전 내용에 대해서 필요한게 아니라면 지우시는게 좋을것 같습니다!

2024-05-16 11:03 UTC, AndroidJeong commented on build.gradle.kts
> +//}
저 부분이 나중에 필요할 수도 있어서 남겨놨습니다
추후에 필요없다면 삭제하겠습니다

2024-05-16 11:28 UTC, Winterwood0118 approved these changes
확인했습니다

2024-05-16 12:19 UTC, winteryy requested changes
DB 관련해서 몇 가지 생각해볼 부분이 있어서 리뷰 드렸습니다
나머지는 대체로 문제 없는 코드인 것 같습니다!

2024-05-16 12:19 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
> +    fun deleteData(): List<RoomEntity>
값을 삽입하고 삭제할 땐, 어떤 것을 삽입하고 삭제할지도 정의되어야 합니다!

2024-05-16 12:19 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id : Int? = null,
이건 좀 생각을 해야하봐야 하는 부분인데, video의 경우 자체적인 id 값을 youtube로부터 받아오게 됩니다.
해당 값을 Primary key로 사용할 수도 있을 것 같습니다. 만약 DB만을 위한 Primary Key를 생성한다고 하더라도, 다른 화면에서의 쓰임을 생각하면 받아온 id 값도 가지고 있어야 할 것 같습니다.

조금은 복잡한 개념인데 데이터 베이스 설계 시에 Primary key는 고유해야 하며, 다른 고유한 식별자는 "후보 키"가 될 수 있습니다. 무엇을 Primary key로 설정할지는, 해당 데이터가 어디서 쓰이는지, 상호 변환 시 어떤 문제가 발생할 수 있을지 예상해보는 것이 도움 될 것 같습니다!

2024-05-16 12:19 UTC, winteryy commented on app/src/main/java/com/example/ymediaapp/presentation/main/MainActivity.kt
> +
네비게이션 잘 사용하신 것 같습니다!

2024-05-16 12:19 UTC, winteryy commented on gradle/libs.versions.toml
> +safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationUiKtx" }
작성하시느라 고생하셨습니다, 덕분에 모르던 부분을 함께 공부하게 되어 좋았습니다

2024-05-16 12:23 UTC, merged

2024-05-17 01:29 UTC, AndroidJeong commented on gradle/libs.versions.toml
> +safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationUiKtx" }
👍👍👍

2024-05-17 01:29 UTC, AndroidJeong commented on app/src/main/java/com/example/ymediaapp/presentation/main/MainActivity.kt
> +
👍👍👍

2024-05-17 01:36 UTC, AndroidJeong commented on app/src/main/java/com/example/ymediaapp/data/database/RoomEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id : Int? = null,
일단 ColumnInfo에 id 추가하는 방향으로 수정했습니다
추후 PrimaryKey 변경이 필요하면 다시 수정하겠습니다!

2024-05-17 01:44 UTC, AndroidJeong commented on app/src/main/java/com/example/ymediaapp/data/database/RoomDao.kt
> +    fun deleteData(): List<RoomEntity>
수정했습니다